// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'SanityContent': typeof import('../node_modules/@nuxtjs/sanity/dist/components/sanity-content.js')['default'],
    'SanityFile': typeof import('../node_modules/@nuxtjs/sanity/dist/components/sanity-file.js')['default'],
    'SanityImage': typeof import('../node_modules/@nuxtjs/sanity/dist/components/sanity-image.js')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
