// Generated by nuxi
/// <reference types="@nuxtjs/sanity" />
/// <reference path="nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path="plugins.d.ts" />
/// <reference types="vue-router" />
/// <reference path="auto-imports.d.ts" />

export {}
